"""add schedule last_attempted_at cursor

Revision ID: 32db7040007d
Revises: 45af93286758
Create Date: 2026-09-19 01:26:54.698448

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32db7040007d"
down_revision: Union[str, Sequence[str], None] = "45af93286758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules", sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "last_attempted_at")
    # ### end Alembic commands ###
