"""add schedules and report_templates, add output_format

Revision ID: 4b652dd146c4
Revises: 81e3a6fe3c75
Create Date: 2026-08-06 23:47:08.958355

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b652dd146c4"
down_revision: Union[str, Sequence[str], None] = "81e3a6fe3c75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector", sa.String(length=50), nullable=False),
        sa.Column("board_id", sa.String(length=100), nullable=True),
        sa.Column("sprint_id", sa.String(length=100), nullable=True),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("output_format", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("reports", sa.Column("output_format", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "output_format")
    op.drop_table("schedules")
    op.drop_table("report_templates")
    # ### end Alembic commands ###
