apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reportapi.fullname" . }}-secrets
  labels:
    {{- include "reportapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := omit .Values.envSecret "DATABASE_URL" "REDIS_URL" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DATABASE_URL: {{ include "reportapi.databaseUrl" . | quote }}
  REDIS_URL: {{ include "reportapi.redisUrl" . | quote }}
