apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reportapi.fullname" . }}-secrets
  labels:
    {{- include "reportapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
